In [1]:
import numpy as np

In [2]:
d = [1,2,3,4,5,6]
arr = np.array(d)
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
arr.dtype

dtype('int64')

In [5]:
np.shape(arr)

(6,)

In [6]:
#criando um array vazio
np.empty(6, dtype='int32')

array([          0,           0,           0,           0,           0,
       -2147483648], dtype=int32)

Operações Matemáticas com numpy

In [8]:
arr1 = np.random.randint(0,100, size=(2,4))
arr1

array([[62, 23, 68, 25],
       [ 9,  9, 18, 82]], dtype=int32)

In [9]:
arr2 = arr1 * 2
arr2

array([[124,  46, 136,  50],
       [ 18,  18,  36, 164]], dtype=int32)

In [11]:
#criando um array de outra forma
arr3 = np.arange(8)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7])

In [14]:
#fazendo o reshape do array
arr4 = arr3.reshape(4,2)
arr4

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [15]:
#Matriz transposta
arr5 = arr4.T
arr5

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])